import React, { createContext, useContext, useState, useEffect, useCallback, useMemo } from 'react';

// Translation strings
const translations = {
  en: {
    // Common
    search: 'Search',
    add: 'Add',
    edit: 'Edit',
    delete: 'Delete',
    download: 'Download',
    share: 'Share',
    view: 'View',
    save: 'Save',
    cancel: 'Cancel',
    confirm: 'Confirm',
    close: 'Close',
    loading: 'Loading...',
    noData: 'No data found',
    actions: 'Actions',
    active: 'Active',
    inactive: 'Inactive',
    all: 'All',
    yes: 'Yes',
    no: 'No',
    refresh: 'Refresh',
    points: 'points',
    days: 'days',
    
    // Navigation
    dashboard: 'Dashboard',
    analytics: 'Analytics',
    pos: 'Point of Sale',
    items: 'Items',
    inventory: 'Inventory',
    stockTransfers: 'Stock Transfers',
    uploadHistory: 'Upload History',
    sales: 'Sales',
    salesDashboard: 'Sales Dashboard',
    quotations: 'Quotations',
    orders: 'Orders',
    invoices: 'Invoices',
    pricing: 'Pricing',
    delivery: 'Delivery',
    returns: 'Returns',
    reports: 'Reports',
    crm: 'CRM',
    purchases: 'Purchases',
    purchaseReturns: 'Purchase Returns',
    purchaseReports: 'Purchase Reports',
    customers: 'Customers',
    customerLedger: 'Customer Ledger',
    suppliers: 'Suppliers',
    supplierLedger: 'Supplier Ledger',
    vouchers: 'Vouchers',
    discountManager: 'Discount Manager',
    loyaltyProgram: 'Loyalty Program',
    stores: 'Stores',
    employees: 'Employees',
    attendance: 'Attendance',
    employeeRatings: 'Employee Ratings',
    payroll: 'Payroll',
    rbacPermissions: 'RBAC Permissions',
    salaryCalculator: 'Salary Calculator',
    settings: 'Settings',
    userManagement: 'User Management',
    invoiceSettings: 'Invoice Settings',
    discountsOffers: 'Discounts & Offers',
    hrManagement: 'HR Management',
    partiesLedger: 'Parties & Ledger',
    purchase: 'Purchase',
    
    // Items Page
    itemsManagement: 'Items Management',
    addItem: 'Add Item',
    editItem: 'Edit Item',
    itemName: 'Item Name',
    sku: 'SKU',
    category: 'Category',
    brand: 'Brand',
    description: 'Description',
    unit: 'Unit',
    mrp: 'MRP',
    sellingPrice: 'Selling Price',
    costPrice: 'Cost Price',
    wholesalePrice: 'Wholesale Price',
    stock: 'Stock',
    inStock: 'in stock',
    lowStock: 'Low Stock',
    outOfStock: 'Out of Stock',
    variants: 'Variants',
    size: 'Size',
    color: 'Color',
    barcode: 'Barcode',
    images: 'Images',
    addImages: 'Add Images',
    uploadImages: 'Upload Images',
    deleteImage: 'Delete Image',
    basicDetails: 'Basic Details',
    pricingTax: 'Pricing & Tax',
    allowReturns: 'Allow Returns',
    allowDiscounts: 'Allow Discounts',
    printBarcodes: 'Print Barcodes',
    addManually: 'Add Manually',
    smartScanner: 'Smart Stock Scanner',
    exportPDF: 'Export PDF',
    exportExcel: 'Export Excel',
    shareWhatsApp: 'Share on WhatsApp',
    viewDetails: 'View Details',
    catalogue: 'Catalogue',
    
    // POS
    selectCustomer: 'Select Customer',
    walkInCustomer: 'Walk-in Customer',
    cart: 'Cart',
    addToCart: 'Add to Cart',
    removeFromCart: 'Remove',
    quantity: 'Quantity',
    subtotal: 'Subtotal',
    discount: 'Discount',
    tax: 'Tax',
    total: 'Total',
    checkout: 'Checkout',
    paymentMethod: 'Payment Method',
    cash: 'Cash',
    card: 'Card',
    upi: 'UPI',
    credit: 'Credit',
    amountReceived: 'Amount Received',
    change: 'Change',
    completeSale: 'Complete Sale',
    
    // User Management
    createUser: 'Create User',
    fullName: 'Full Name',
    email: 'Email',
    password: 'Password',
    role: 'Role',
    admin: 'Admin',
    manager: 'Manager',
    staff: 'Staff',
    cashier: 'Cashier',
    permissions: 'Permissions',
    assignedStores: 'Assigned Stores',
    deactivateUser: 'Deactivate User',
    activateUser: 'Activate User',
    auditTrail: 'Audit Trail',
    
    // Loyalty Program
    loyaltyDescription: 'Reward your customers and build loyalty',
    programActive: 'Program Active',
    programInactive: 'Program Inactive',
    earning: 'Earning',
    pointPer100: 'point per ₹100 spent',
    enableInSettings: 'Enable the program in settings',
    pointsValue: 'Points Value',
    perPoint: 'per point',
    minRedeem: 'Min. Redeem',
    maxRedeem: 'Max Redeem',
    ofBill: 'of bill',
    pointExpiry: 'Point Expiry',
    membershipTiers: 'Membership Tiers',
    leaderboard: 'Leaderboard',
    chooseTier: 'Choose Your Membership',
    tierDescription: 'Unlock exclusive benefits as you earn more points',
    topLoyalCustomers: 'Top Loyal Customers',
    noPointsYet: 'No customers have earned points yet',
    customerLoyalty: 'Customer Loyalty',
    searchCustomers: 'Search customers...',
    loyaltySettings: 'Loyalty Program Settings',
    programStatus: 'Program Status',
    enableDisable: 'Enable or disable the loyalty program',
    pointsPer100: 'Points per ₹100 spent',
    pointValue: 'Point Value (₹)',
    minPointsRedeem: 'Minimum Points to Redeem',
    maxBillPercent: 'Max Bill % Payable via Points',
    pointExpiryDays: 'Point Expiry (Days)',
    saveSettings: 'Save Settings',
    loyalty: 'Loyalty',
    totalPoints: 'Total Points',
    benefits: 'Benefits',
    recentTransactions: 'Recent Transactions',
    noTransactions: 'No transactions yet',
    
    // Settings
    language: 'Language',
    selectLanguage: 'Select Language',
    english: 'English',
    hindi: 'Hindi',
    theme: 'Theme',
    light: 'Light',
    dark: 'Dark',
    currency: 'Currency',
    categories: 'Categories',
    brands: 'Brands',
    
    // Dashboard
    quickActions: 'Quick Actions',
    overview: 'Overview',
    totalItems: 'Total Items',
    todayRevenue: 'Today Revenue',
    todayOrders: 'Today Orders',
    lowStockItems: 'Low Stock Items',
    pendingTransfers: 'Pending Transfers',
    recentSales: 'Recent Sales',
    noSalesYet: 'No sales yet',
    allItemsStocked: 'All items well stocked',
    backupAvailable: 'Backup Available',
    restoreData: 'Restore your data from the backup file',
    restoreBtn: 'Restore Data',
    
    // Messages
    confirmDelete: 'Are you sure you want to delete this?',
    deleteSuccess: 'Deleted successfully',
    saveSuccess: 'Saved successfully',
    updateSuccess: 'Updated successfully',
    createSuccess: 'Created successfully',
    errorOccurred: 'An error occurred',
    noItemsFound: 'No items found',
    noResultsFound: 'No results found',
    welcomeBack: 'Welcome back',
    logout: 'Logout',
    builtForRetail: 'घंटों का हिसाब, अब मिनटों में',
  },
  
  hi: {
    // Common
    search: 'खोजें',
    add: 'जोड़ें',
    edit: 'संपादित करें',
    delete: 'हटाएं',
    download: 'डाउनलोड',
    share: 'शेयर करें',
    view: 'देखें',
    save: 'सहेजें',
    cancel: 'रद्द करें',
    confirm: 'पुष्टि करें',
    close: 'बंद करें',
    loading: 'लोड हो रहा है...',
    noData: 'कोई डेटा नहीं मिला',
    actions: 'कार्रवाई',
    active: 'सक्रिय',
    inactive: 'निष्क्रिय',
    all: 'सभी',
    yes: 'हाँ',
    no: 'नहीं',
    refresh: 'रिफ्रेश',
    points: 'पॉइंट्स',
    days: 'दिन',
    
    // Navigation
    dashboard: 'डैशबोर्ड',
    analytics: 'एनालिटिक्स',
    pos: 'पॉइंट ऑफ सेल',
    items: 'आइटम',
    inventory: 'इन्वेंटरी',
    stockTransfers: 'स्टॉक ट्रांसफर',
    uploadHistory: 'अपलोड हिस्ट्री',
    sales: 'बिक्री',
    salesDashboard: 'बिक्री डैशबोर्ड',
    quotations: 'कोटेशन',
    orders: 'ऑर्डर',
    invoices: 'इनवॉइस',
    pricing: 'मूल्य निर्धारण',
    delivery: 'डिलीवरी',
    returns: 'रिटर्न',
    reports: 'रिपोर्ट',
    crm: 'सीआरएम',
    purchases: 'खरीदारी',
    purchaseReturns: 'खरीदारी रिटर्न',
    purchaseReports: 'खरीदारी रिपोर्ट',
    customers: 'ग्राहक',
    customerLedger: 'ग्राहक खाता',
    suppliers: 'आपूर्तिकर्ता',
    supplierLedger: 'आपूर्तिकर्ता खाता',
    vouchers: 'वाउचर',
    discountManager: 'छूट प्रबंधक',
    loyaltyProgram: 'लॉयल्टी प्रोग्राम',
    stores: 'स्टोर',
    employees: 'कर्मचारी',
    attendance: 'उपस्थिति',
    employeeRatings: 'कर्मचारी रेटिंग',
    payroll: 'पेरोल',
    rbacPermissions: 'RBAC अनुमतियाँ',
    salaryCalculator: 'वेतन कैलकुलेटर',
    settings: 'सेटिंग्स',
    userManagement: 'उपयोगकर्ता प्रबंधन',
    invoiceSettings: 'इनवॉइस सेटिंग्स',
    discountsOffers: 'छूट और ऑफर',
    hrManagement: 'मानव संसाधन प्रबंधन',
    partiesLedger: 'पार्टी और खाता',
    purchase: 'खरीद',
    
    // Items Page
    itemsManagement: 'आइटम प्रबंधन',
    addItem: 'आइटम जोड़ें',
    editItem: 'आइटम संपादित करें',
    itemName: 'आइटम का नाम',
    sku: 'एसकेयू',
    category: 'श्रेणी',
    brand: 'ब्रांड',
    description: 'विवरण',
    unit: 'इकाई',
    mrp: 'एमआरपी',
    sellingPrice: 'बिक्री मूल्य',
    costPrice: 'लागत मूल्य',
    wholesalePrice: 'थोक मूल्य',
    stock: 'स्टॉक',
    inStock: 'स्टॉक में',
    lowStock: 'कम स्टॉक',
    outOfStock: 'स्टॉक खत्म',
    variants: 'वेरिएंट',
    size: 'साइज़',
    color: 'रंग',
    barcode: 'बारकोड',
    images: 'चित्र',
    addImages: 'चित्र जोड़ें',
    uploadImages: 'चित्र अपलोड करें',
    deleteImage: 'चित्र हटाएं',
    basicDetails: 'मूल विवरण',
    pricingTax: 'मूल्य और कर',
    allowReturns: 'रिटर्न की अनुमति',
    allowDiscounts: 'छूट की अनुमति',
    printBarcodes: 'बारकोड प्रिंट करें',
    addManually: 'मैन्युअल रूप से जोड़ें',
    smartScanner: 'स्मार्ट स्टॉक स्कैनर',
    exportPDF: 'पीडीएफ निर्यात करें',
    exportExcel: 'एक्सेल निर्यात करें',
    shareWhatsApp: 'व्हाट्सएप पर शेयर करें',
    viewDetails: 'विवरण देखें',
    catalogue: 'कैटलॉग',
    
    // POS
    selectCustomer: 'ग्राहक चुनें',
    walkInCustomer: 'वॉक-इन ग्राहक',
    cart: 'कार्ट',
    addToCart: 'कार्ट में जोड़ें',
    removeFromCart: 'हटाएं',
    quantity: 'मात्रा',
    subtotal: 'उप-योग',
    discount: 'छूट',
    tax: 'कर',
    total: 'कुल',
    checkout: 'चेकआउट',
    paymentMethod: 'भुगतान का तरीका',
    cash: 'नकद',
    card: 'कार्ड',
    upi: 'यूपीआई',
    credit: 'क्रेडिट',
    amountReceived: 'प्राप्त राशि',
    change: 'वापसी',
    completeSale: 'बिक्री पूर्ण करें',
    
    // User Management
    createUser: 'उपयोगकर्ता बनाएं',
    fullName: 'पूरा नाम',
    email: 'ईमेल',
    password: 'पासवर्ड',
    role: 'भूमिका',
    admin: 'एडमिन',
    manager: 'मैनेजर',
    staff: 'स्टाफ',
    cashier: 'कैशियर',
    permissions: 'अनुमतियाँ',
    assignedStores: 'सौंपे गए स्टोर',
    deactivateUser: 'उपयोगकर्ता निष्क्रिय करें',
    activateUser: 'उपयोगकर्ता सक्रिय करें',
    auditTrail: 'ऑडिट ट्रेल',
    
    // Loyalty Program
    loyaltyDescription: 'अपने ग्राहकों को पुरस्कृत करें और वफादारी बनाएं',
    programActive: 'प्रोग्राम सक्रिय',
    programInactive: 'प्रोग्राम निष्क्रिय',
    earning: 'कमाई',
    pointPer100: 'पॉइंट प्रति ₹100 खर्च',
    enableInSettings: 'सेटिंग्स में प्रोग्राम सक्षम करें',
    pointsValue: 'पॉइंट्स मूल्य',
    perPoint: 'प्रति पॉइंट',
    minRedeem: 'न्यूनतम रिडीम',
    maxRedeem: 'अधिकतम रिडीम',
    ofBill: 'बिल का',
    pointExpiry: 'पॉइंट समाप्ति',
    membershipTiers: 'सदस्यता स्तर',
    leaderboard: 'लीडरबोर्ड',
    chooseTier: 'अपनी सदस्यता चुनें',
    tierDescription: 'अधिक पॉइंट्स कमाकर विशेष लाभ अनलॉक करें',
    topLoyalCustomers: 'शीर्ष वफादार ग्राहक',
    noPointsYet: 'अभी तक किसी ग्राहक ने पॉइंट्स नहीं कमाए',
    customerLoyalty: 'ग्राहक वफादारी',
    searchCustomers: 'ग्राहक खोजें...',
    loyaltySettings: 'लॉयल्टी प्रोग्राम सेटिंग्स',
    programStatus: 'प्रोग्राम स्थिति',
    enableDisable: 'लॉयल्टी प्रोग्राम सक्षम या अक्षम करें',
    pointsPer100: '₹100 खर्च पर पॉइंट्स',
    pointValue: 'पॉइंट मूल्य (₹)',
    minPointsRedeem: 'न्यूनतम रिडीम पॉइंट्स',
    maxBillPercent: 'पॉइंट्स से अधिकतम बिल %',
    pointExpiryDays: 'पॉइंट समाप्ति (दिन)',
    saveSettings: 'सेटिंग्स सहेजें',
    loyalty: 'वफादारी',
    totalPoints: 'कुल पॉइंट्स',
    benefits: 'लाभ',
    recentTransactions: 'हालिया लेनदेन',
    noTransactions: 'अभी तक कोई लेनदेन नहीं',
    
    // Settings
    language: 'भाषा',
    selectLanguage: 'भाषा चुनें',
    english: 'अंग्रेज़ी',
    hindi: 'हिन्दी',
    theme: 'थीम',
    light: 'लाइट',
    dark: 'डार्क',
    currency: 'मुद्रा',
    categories: 'श्रेणियाँ',
    brands: 'ब्रांड',
    
    // Dashboard
    quickActions: 'त्वरित कार्रवाई',
    overview: 'सिंहावलोकन',
    totalItems: 'कुल आइटम',
    todayRevenue: 'आज की आय',
    todayOrders: 'आज के ऑर्डर',
    lowStockItems: 'कम स्टॉक आइटम',
    pendingTransfers: 'लंबित ट्रांसफर',
    recentSales: 'हालिया बिक्री',
    noSalesYet: 'अभी तक कोई बिक्री नहीं',
    allItemsStocked: 'सभी आइटम स्टॉक में',
    backupAvailable: 'बैकअप उपलब्ध',
    restoreData: 'बैकअप फ़ाइल से अपना डेटा पुनर्स्थापित करें',
    restoreBtn: 'डेटा पुनर्स्थापित करें',
    
    // Messages
    confirmDelete: 'क्या आप वाकई इसे हटाना चाहते हैं?',
    deleteSuccess: 'सफलतापूर्वक हटाया गया',
    saveSuccess: 'सफलतापूर्वक सहेजा गया',
    updateSuccess: 'सफलतापूर्वक अपडेट किया गया',
    createSuccess: 'सफलतापूर्वक बनाया गया',
    errorOccurred: 'एक त्रुटि हुई',
    noItemsFound: 'कोई आइटम नहीं मिला',
    noResultsFound: 'कोई परिणाम नहीं मिला',
    welcomeBack: 'वापस स्वागत है',
    logout: 'लॉगआउट',
    builtForRetail: 'खुदरा विकास के लिए बनाया गया',
  }
};

const LanguageContext = createContext(null);

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState(() => {
    const saved = localStorage.getItem('language');
    return saved || 'en';
  });

  useEffect(() => {
    localStorage.setItem('language', language);
    // Update HTML lang attribute
    document.documentElement.lang = language;
  }, [language]);

  // Translation function - memoized to prevent re-renders
  const t = useCallback((key) => {
    return translations[language]?.[key] || translations['en']?.[key] || key;
  }, [language]);

  // Get all translations for current language
  const getTranslations = useCallback(() => translations[language] || translations['en'], [language]);

  // Memoize context value to prevent unnecessary re-renders
  const value = useMemo(() => ({
    language,
    setLanguage,
    t,
    getTranslations,
    availableLanguages: [
      { code: 'en', name: 'English', nativeName: 'English' },
      { code: 'hi', name: 'Hindi', nativeName: 'हिन्दी' }
    ]
  }), [language, t, getTranslations]);

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
};

export default LanguageContext;
